services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nyam_server
    restart: unless-stopped


  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
      -
  nyam_kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nyam-elasticsearch:
    build:
      context: ./elasticsearch
    image: nyam-elasticsearch:8.12.0-nori
    container_name: nyam-elasticsearch
    restart: always
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    networks:
      - nyam_server

networks:
  nyam_server:
    external: true