spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost}:${SPRING_DATASOURCE_PORT:5432}/everyday?currentSchema=everyday
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc batch size ??
        jdbc:
          batch_size: 500
    show_sql: true

# MongoDB 관련 설정
  data:
    mongodb:
      # 로컬에서 MongoDB 사용할떈 아래의 코드 사용
#      uri: mongodb://${LOCAL_MONGO_USERNAME}:${LOCAL_MONGO_PASSWORD}@${LOCAL_MONGO_HOST_ADDRESS}:${LOCAL_MONGO_PORT}/${LOCAL_MONGO_DBNAME}?authSource=admin&tls=false&retryWrites=true&appName=nyamnyamMongo
      # Mongo를 Atlas 기반으로 사용하기 위한다면 아래 코드 주석처리 해제
      uri: mongodb+srv://${ATLAS_MONGO_USERNAME}:${ATLAS_MONGO_PASSWORD}@${ATLAS_MONGO_HOST_ADDRESS}/?retryWrites=true&w=majority&appName=nyamnyamMongo
      database: ${MONGO_DBNAME}

# AWS S3 적용을 위한 세팅
cloud:
  aws:
    s3:
      bucketName : ${AWSS3_BUCKETNAME}
    stack:
      auto: false
    region:
      static: ${AWSS3_REGION}
    credentials:
      secret-key: ${IAM_SECRET_KEY}
      access-key: ${IAM_ACCESS_KEY}


---

#Redis
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# OAuth2 설정 예시
# 우선 미사용 처리
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
            client-name: Google
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://openidconnect.googleapis.com/v1/userinfo"
            user-name-attribute: sub
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id


openapi:
  nutri:
    base-url: http://api.data.go.kr/openapi/tn_pubr_public_nutri_process_info_api
    service-key: ${NUTRI_API_KEY}   # 환경변수에서 주입
    default-page-size: 100
    connect-timeout: 5s
    read-timeout: 120s