CREATE SCHEMA IF NOT EXISTS everyday;
SET search_path TO everyday;

CREATE SCHEMA IF NOT EXISTS everyday;
SET search_path TO everyday;

CREATE TABLE member (
                        member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        provider_id VARCHAR(50) NOT NULL,
                        nickname VARCHAR(20) NOT NULL,
                        email VARCHAR(50),
                        member_img VARCHAR(255) NOT NULL,
                        gender VARCHAR(1) NOT NULL,
                        height NUMERIC(4,1) NOT NULL,
                        weight NUMERIC(4,1) NOT NULL,
                        role VARCHAR(10) NOT NULL DEFAULT 'USER',
                        age BIGINT NOT NULL,
                        member_status VARCHAR(20),
                        target_weight NUMERIC(4,1),
                        activity_level VARCHAR(20),
                        last_login_date TIMESTAMP,
                        consecutive_login_days BIGINT,
                        created_date TIMESTAMP NOT NULL,
                        modified_date TIMESTAMP NOT NULL,
                        PRIMARY KEY (member_id)
);

CREATE TABLE auth (
                      auth_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      member_id BIGINT NOT NULL,
                      token_type VARCHAR(255) NOT NULL,
                      access_token VARCHAR(255) NOT NULL,
                      refresh_token VARCHAR(255) NOT NULL,
                      created_date TIMESTAMP NOT NULL,
                      modified_date TIMESTAMP NOT NULL,
                      PRIMARY KEY (auth_id)
);

CREATE TABLE member_meal_log (
                                 meal_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 member_id BIGINT NOT NULL,
                                 food_id BIGINT NOT NULL,
                                 meal_log_date DATE NOT NULL,
                                 intake_amount INT NOT NULL,
                                 intake_kcal NUMERIC(6,1) NOT NULL,
                                 meal_type VARCHAR(16) NOT NULL,
                                 carbohydrate NUMERIC(4,1) NOT NULL,
                                 protein NUMERIC(4,1) NOT NULL,
                                 fat NUMERIC(4,1) NOT NULL,
                                 created_date TIMESTAMP NOT NULL,
                                 modified_date TIMESTAMP NOT NULL,
                                 PRIMARY KEY (meal_log_id)
);

CREATE TABLE member_daily_summary (
                                      member_daily_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      member_id BIGINT NOT NULL,
                                      summary_date DATE NOT NULL,
                                      weight NUMERIC(4,1) NOT NULL,
                                      total_protein NUMERIC(5,1) NOT NULL,
                                      total_carbohydrate NUMERIC(5,1) NOT NULL,
                                      total_fat NUMERIC(5,1) NOT NULL,
                                      total_water NUMERIC(5,1) NOT NULL,
                                      total_kcal NUMERIC(6,1) NOT NULL,
                                      created_date TIMESTAMP NOT NULL,
                                      modified_date TIMESTAMP NOT NULL,
                                      PRIMARY KEY (member_daily_id)
);

CREATE TABLE board (
                       board_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       member_id BIGINT NOT NULL,
                       board_title VARCHAR(100) NOT NULL,
                       board_content VARCHAR(255) NOT NULL,
                       view_count NUMERIC(20) NOT NULL,
                       like_count BIGINT NOT NULL DEFAULT 0,
                       comment_count BIGINT NOT NULL DEFAULT 0,
                       board_type VARCHAR(20) NOT NULL,
                       created_date TIMESTAMP NOT NULL,
                       modified_date TIMESTAMP NOT NULL,
                       PRIMARY KEY (board_id)
);

CREATE TABLE board_comment (
                               comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               member_id BIGINT NOT NULL,
                               board_id BIGINT NOT NULL,
                               parent_id BIGINT,
                               content VARCHAR(100) NOT NULL,
                               created_date TIMESTAMP NOT NULL,
                               modified_date TIMESTAMP NOT NULL,
                               PRIMARY KEY (comment_id)
);

CREATE TABLE board_like (
                            board_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            member_id BIGINT NOT NULL,
                            board_id BIGINT NOT NULL,
                            created_date TIMESTAMP NOT NULL,
                            PRIMARY KEY (board_like_id)
);

CREATE TABLE bookmark (
                          bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          member_id BIGINT NOT NULL,
                          board_id BIGINT NOT NULL,
                          created_date TIMESTAMP NOT NULL,
                          PRIMARY KEY (bookmark_id)
);

CREATE TABLE food (
                      food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      food_name varchar(50) NOT NULL,
                      manufacturer varchar(50),
                      unit_kcal decimal(4,1) NOT NULL,
                      unit_gram bigint NOT NULL,
                      food_size int
);

CREATE TABLE nutrition_category (
                                    food_cate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    category varchar(10) NOT NULL
);

CREATE TABLE nutrition_detail (
                                  nutrition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  food_id bigint NOT NULL,
                                  food_cate_id bigint NOT NULL,
                                  nutrition_nm varchar(50) NOT NULL,
                                  amount numeric(4,1) NOT NULL,
                                  unit_weight bigint NOT NULL
);

CREATE TABLE team (
                      team_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      member_id BIGINT NOT NULL,
                      team_title VARCHAR(100) NOT NULL,
                      team_description VARCHAR(255),
                      team_img VARCHAR(255) NOT NULL,
                      team_current_members INT NOT NULL DEFAULT 1,
                      team_max_members BIGINT NOT NULL DEFAULT 6,
                      created_date TIMESTAMP NOT NULL,
                      modified_date TIMESTAMP NOT NULL,
                      PRIMARY KEY (team_id)
);

CREATE TABLE team_member_status (
                                    team_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    member_id BIGINT NOT NULL,
                                    team_id BIGINT NOT NULL,
                                    status VARCHAR(10) NOT NULL,
                                    created_date TIMESTAMP NOT NULL,
                                    modified_date TIMESTAMP NOT NULL,
                                    team_role VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
                                    banned_reason VARCHAR(255),
                                    banned_date TIMESTAMP,
                                    left_date TIMESTAMP,
                                    PRIMARY KEY (team_member_id)
);

CREATE TABLE team_notification (
                                   team_alarm_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   team_id BIGINT NOT NULL,
                                   member_id BIGINT NOT NULL,
                                   notification_type VARCHAR(1) NOT NULL,
                                   team_noty_content VARCHAR(255) NOT NULL,
                                   is_checked BOOLEAN NOT NULL default false,
                                   created_date TIMESTAMP NOT NULL,
                                   PRIMARY KEY (team_alarm_id)
);

CREATE TABLE team_activity_feed (
                                    feed_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    member_id BIGINT NOT NULL,
                                    team_id BIGINT NOT NULL,
                                    is_modified BOOL NOT NULL DEFAULT false,
                                    activity_type VARCHAR(20) NOT NULL,
                                    activity_content VARCHAR(20),
                                    created_date TIMESTAMP NOT NULL,
                                    PRIMARY KEY (feed_id)
);

CREATE TABLE chat_room (
                           chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           team_id BIGINT NOT NULL,
                           PRIMARY KEY (chat_room_id)
);

CREATE TABLE team_notice (
                             team_notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             member_id BIGINT NOT NULL,
                             team_id BIGINT NOT NULL,
                             title VARCHAR(255) NOT NULL,
                             content VARCHAR(255),
                             created_date TIMESTAMP NOT NULL,
                             modified_date TIMESTAMP NOT NULL,
                             PRIMARY KEY (team_notice_id)
);

CREATE TABLE chat_detail (
                             chat_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             chat_room_id BIGINT NOT NULL,
                             member_id BIGINT NOT NULL,
                             chat_content VARCHAR(255) NOT NULL,
                             created_date TIMESTAMP NOT NULL,
                             PRIMARY KEY (chat_detail_id)
);

CREATE TABLE challenge (
                           challenge_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           badge_id BIGINT NOT NULL,
                           title VARCHAR(30) NOT NULL,
                           description VARCHAR(255) NOT NULL,
                           challenge_code VARCHAR(50) NOT NULL,
                           type VARCHAR(30) NOT NULL,
                           start_date TIMESTAMP,
                           end_date TIMESTAMP,
                           PRIMARY KEY (challenge_id)
);

CREATE TABLE member_challenge_status (
                                         member_challenge_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                         member_id BIGINT NOT NULL,
                                         challenge_id BIGINT NOT NULL,
                                         is_cleared BOOL NOT NULL DEFAULT false,
                                         progress_count INT NOT NULL DEFAULT 0,
                                         created_date TIMESTAMP NOT NULL,
                                         modified_date TIMESTAMP NOT NULL,
                                         PRIMARY KEY (member_challenge_status_id)
);

CREATE TABLE badge (
                       badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       badge_image VARCHAR(255) NOT NULL,
                       badge_type VARCHAR(50) NOT NULL,
                       created_date TIMESTAMP NOT NULL,
                       PRIMARY KEY (badge_id)
);

CREATE TABLE score_log (
                           score_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           member_id BIGINT NOT NULL,
                           scored_on DATE,
                           score_amount BIGINT NOT NULL,
                           meal_type VARCHAR(10) NOT NULL,
                           source_type VARCHAR(50) NOT NULL,
                           created_date TIMESTAMP NOT NULL,
                           PRIMARY KEY (score_log_id)
);

CREATE TABLE member_badge_status (
                                     mbs_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     member_id BIGINT NOT NULL,
                                     badge_id BIGINT NOT NULL,
                                     created_date TIMESTAMP NOT NULL,
                                     PRIMARY KEY (mbs_id)
);

CREATE TABLE notification (
                              notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              member_id BIGINT,
                              notification_content VARCHAR(255) NOT NULL,
                              notification_type VARCHAR(20) NOT NULL,
                              created_date TIMESTAMP NOT NULL,
                              PRIMARY KEY (notification_id)
);

CREATE TABLE member_notification_status (
                                            member_id BIGINT NOT NULL,
                                            last_notification_num BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE member_global_ranking (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       ranking_year INT NOT NULL,
                                       ranking_month INT NOT NULL,
                                       member_id BIGINT NOT NULL,
                                       score INT NOT NULL,
                                       rank INT NOT NULL,
                                       created_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE member_team_ranking (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     ranking_year INT NOT NULL,
                                     ranking_week INT NOT NULL,
                                     team_id BIGINT NOT NULL,
                                     member_id BIGINT NOT NULL,
                                     rank_in_team INT NOT NULL,
                                     score INT NOT NULL,
                                     created_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE team_global_ranking (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     ranking_year INT NOT NULL,
                                     ranking_month INT NOT NULL,
                                     team_id BIGINT NOT NULL,
                                     rank INT NOT NULL,
                                     average_score NUMERIC(10,2) NOT NULL,
                                     total_score BIGINT NOT NULL,
                                     member_count INT NOT NULL,
                                     created_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE mission (
                         mission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         category VARCHAR(50) NOT NULL,
                         title VARCHAR(255) NOT NULL,
                         type VARCHAR(20) NOT NULL,
                         is_active BOOLEAN NOT NULL DEFAULT true,
                         created_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE daily_mission (
                               daily_mission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               member_id BIGINT NOT NULL,
                               mission_id BIGINT NOT NULL,
                               mission_date DATE NOT NULL,
                               is_completed BOOLEAN NOT NULL DEFAULT false,
                               completed_date TIMESTAMP,
                               completed_by VARCHAR(16) NOT NULL DEFAULT 'NONE',
                               created_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                               modified_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                               expire_date TIMESTAMP NOT NULL
);

CREATE TABLE daily_mission_stamp (
                                     stamp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     member_id BIGINT NOT NULL,
                                     mission_date DATE NOT NULL,
                                     completed_count INT NOT NULL,
                                     achieved BOOLEAN NOT NULL,
                                     issued_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE shedlock (
                          name varchar(64) PRIMARY KEY,
                          lock_until timestamp(3) NOT NULL,
                          locked_at timestamp(3) NOT NULL,
                          locked_by varchar(255) NOT NULL
);

CREATE INDEX idx_member_daily_summary_member_date ON member_daily_summary (member_id, summary_date);

CREATE INDEX IDX_BOARD_COMMENT_PARENT ON board_comment (parent_id);

CREATE INDEX idx_board_comment_modified_date ON board_comment (modified_date);

CREATE UNIQUE INDEX uq_food_name_mfr ON food (food_name, manufacturer);

CREATE UNIQUE INDEX ux_nd_food_cate_nm ON nutrition_detail (food_id, food_cate_id, nutrition_nm);

CREATE UNIQUE INDEX ON team_member_status (member_id, team_id);

CREATE INDEX idx_member_global_ranking_month ON member_global_ranking (ranking_year, ranking_month);

CREATE INDEX idx_member_team_ranking ON member_team_ranking (team_id, ranking_week);

CREATE INDEX idx_team_global_ranking ON team_global_ranking (team_id, ranking_year, ranking_month);

CREATE UNIQUE INDEX uq_daily ON daily_mission (member_id, mission_id, mission_date);

CREATE INDEX idx_daily_user_date ON daily_mission (member_id, mission_date);

CREATE INDEX idx_daily_expire ON daily_mission (expire_date);

CREATE UNIQUE INDEX uq_daily_mission_stamp ON daily_mission_stamp (member_id, mission_date);

CREATE INDEX idx_daily_mission_stamp_user_date ON daily_mission_stamp (member_id, mission_date);

COMMENT ON COLUMN member.provider_id IS '소셜에서 들어오는 provider';

COMMENT ON COLUMN member.member_img IS 'AWS S3의 URL그대로 기록하기';

COMMENT ON COLUMN member.gender IS 'M,F 중 하나';

COMMENT ON COLUMN member.member_status IS '0:정상, 1:탈퇴, 2:정지';

COMMENT ON COLUMN member_meal_log.intake_amount IS '단위는 항상 g 혹은 ml로 간주';

COMMENT ON COLUMN member_meal_log.intake_kcal IS '그램수, 먹은 양 기반으로 계산해서 저장';

COMMENT ON COLUMN member_meal_log.meal_type IS '0: 아침, 1:점심, 2:저녁, 3:간식 중 하나';

COMMENT ON COLUMN member_daily_summary.total_kcal IS '음식 섭취 기록 작성시에 계산';

COMMENT ON COLUMN board.board_type IS '1: BEFORE_AFTER, 2:RECIPE, 3:FREETALK';

COMMENT ON TABLE food IS '식품 기본 정보';

COMMENT ON TABLE nutrition_category IS '영양소 대분류 (예: 1=탄수화물, 2=단백질, 3=지방, 4=무기질, 5=기타)';

COMMENT ON TABLE nutrition_detail IS '식품별 영양소 상세 (영양소명 기준 유니크)';

COMMENT ON COLUMN team.team_img IS 'AWS의 URL을 그대로 사용합니다';

COMMENT ON COLUMN team_member_status.status IS '0:HOLD, 1:REGIST, 2:APPROVED, 3:REJECT 등';

COMMENT ON COLUMN team_notification.notification_type IS '1:물섭취, 2:칼로리섭취, 3:몸무게변화. 4:챌린지달성 등';

COMMENT ON COLUMN challenge.challenge_code IS '백엔드에서 가질 챌린지 이름';

COMMENT ON COLUMN challenge.type IS 'REGULAR_CHALLENGE, EVENT_CHALLENGE 중 하나';

COMMENT ON COLUMN challenge.start_date IS '진행중인 챌린지 목록 불러올 때 사용';

COMMENT ON COLUMN score_log.meal_type IS 'BREAKFAST, LUNCH, DINNER, SNACK 네 가지';

COMMENT ON COLUMN score_log.source_type IS 'MEAL_INPUT, BADGE_REWARD, CHALLENGE_CLEAR 중 하나';

COMMENT ON COLUMN notification.notification_type IS '그룹 공지, 서버 공지, 가입 신청 왔음, 가입 신청 APPROVED, REJECTED 등';

ALTER TABLE challenge ADD CONSTRAINT FK_badge_TO_challenge FOREIGN KEY (badge_id) REFERENCES badge (badge_id);

ALTER TABLE daily_mission ADD CONSTRAINT fk_daily_mission FOREIGN KEY (mission_id) REFERENCES mission (mission_id);

ALTER TABLE board_comment ADD CONSTRAINT FK_COMMENT_TO_COMMENT FOREIGN KEY (parent_id) REFERENCES board_comment (comment_id);

ALTER TABLE nutrition_detail ADD FOREIGN KEY (food_id) REFERENCES food (food_id);

ALTER TABLE nutrition_detail ADD FOREIGN KEY (food_cate_id) REFERENCES nutrition_category (food_cate_id);

ALTER TABLE team ADD CONSTRAINT FK_member_team FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_notification ADD CONSTRAINT FK_team_member_stauts_TO_team_notification FOREIGN KEY (team_id, member_id) REFERENCES team_member_status (team_id, member_id);

ALTER TABLE team_activity_feed ADD CONSTRAINT FK_team_member_stauts_TO_team_activity_feed FOREIGN KEY (member_id, team_id) REFERENCES team_member_status (member_id, team_id);

ALTER TABLE team_notice ADD CONSTRAINT FK_team_member_status_TO_team_notice FOREIGN KEY (member_id, team_id) REFERENCES team_member_status (member_id, team_id);

ALTER TABLE score_log ADD CONSTRAINT FK_MEMBER_TO_SCORE_LOG FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE auth ADD CONSTRAINT FK_member_TO_auth_1 FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_meal_log ADD CONSTRAINT FK_member_TO_meal_log FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_meal_log ADD CONSTRAINT FK_food_TO_meal_log FOREIGN KEY (food_id) REFERENCES food (food_id);

ALTER TABLE member_daily_summary ADD CONSTRAINT FK_member_TO_summary FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_comment ADD CONSTRAINT FK_member_TO_bcomment FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_comment ADD CONSTRAINT FK_board_TO_bcomment FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE board_like ADD CONSTRAINT FK_member_TO_board_like FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_like ADD CONSTRAINT FK_board_TO_board_like FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE bookmark ADD CONSTRAINT FK_member_TO_bookmark FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE bookmark ADD CONSTRAINT FK_board_TO_bookmark FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE team_member_status ADD CONSTRAINT FK_member_TO_gmstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_member_status ADD CONSTRAINT FK_team_TO_gmstatus FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE chat_room ADD CONSTRAINT FK_team_TO_chat_room FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE chat_detail ADD CONSTRAINT FK_chat_room_TO_cdetail FOREIGN KEY (chat_room_id) REFERENCES chat_room (chat_room_id);

ALTER TABLE chat_detail ADD CONSTRAINT FK_member_TO_cdetail FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_challenge_status ADD CONSTRAINT FK_member_TO_mcstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_challenge_status ADD CONSTRAINT FK_challenge_TO_mcstatus FOREIGN KEY (challenge_id) REFERENCES challenge (challenge_id);

ALTER TABLE member_badge_status ADD CONSTRAINT FK_member_TO_mbstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_badge_status ADD CONSTRAINT FK_badge_TO_mbstqatus FOREIGN KEY (badge_id) REFERENCES badge (badge_id);

ALTER TABLE notification ADD CONSTRAINT FK_member_TO_notification FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_global_ranking ADD CONSTRAINT FK_member_TO_member_global_ranking FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_team_ranking ADD CONSTRAINT FK_team_TO_member_team_ranking FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE member_team_ranking ADD CONSTRAINT FK_member_TO_member_team_ranking FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_global_ranking ADD CONSTRAINT FK_team_TO_team_global_ranking FOREIGN KEY (team_id) REFERENCES team (team_id);
