CREATE SCHEMA IF NOT EXISTS everyday;
SET search_path TO everyday;

CREATE TABLE member (
                        member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        provider_id VARCHAR(50) NOT NULL,
                        nickname VARCHAR(20) NOT NULL,
                        email VARCHAR(50),
                        member_img VARCHAR(255) NOT NULL,
                        gender VARCHAR(1) NOT NULL,
                        height NUMERIC(4,1) NOT NULL,
                        weight NUMERIC(4,1) NOT NULL,
                        role VARCHAR(10) NOT NULL DEFAULT 'USER',
                        age BIGINT NOT NULL,
                        member_status VARCHAR(20),
                        basal_metabolic_rate NUMERIC(6,1),
                        activity_level VARCHAR(20),
                        created_date TIMESTAMP NOT NULL,
                        modified_date TIMESTAMP NOT NULL,
                        PRIMARY KEY (member_id)
);

CREATE TABLE auth (
                      auth_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      member_id BIGINT NOT NULL,
                      token_type VARCHAR(255) NOT NULL,
                      access_token VARCHAR(255) NOT NULL,
                      refresh_token VARCHAR(255) NOT NULL,
                      created_date TIMESTAMP NOT NULL,
                      modified_date TIMESTAMP NOT NULL,
                      PRIMARY KEY (auth_id)
);

CREATE TABLE member_meal_log (
                                 meal_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 member_id BIGINT NOT NULL,
                                 food_id BIGINT NOT NULL,
                                 intake_amount INT NOT NULL,
                                 intake_kcal NUMERIC(6,1) NOT NULL,
                                 meal_type VARCHAR(16) NOT NULL,
                                 created_date TIMESTAMP NOT NULL,
                                 modified_date TIMESTAMP NOT NULL,
                                 carbohydrate NUMERIC(4,1) NOT NULL,
                                 protein NUMERIC(4,1) NOT NULL,
                                 fat NUMERIC(4,1) NOT NULL,
                                 PRIMARY KEY (meal_log_id)
);

CREATE TABLE member_daily_summary (
                                      member_daily_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      member_id BIGINT NOT NULL,
                                      weight NUMERIC(4,1) NOT NULL,
                                      total_protein NUMERIC(5,1) NOT NULL,
                                      total_carbohydrate NUMERIC(5,1) NOT NULL,
                                      total_fat NUMERIC(5,1) NOT NULL,
                                      total_water NUMERIC(5,1) NOT NULL,
                                      total_kcal INT NOT NULL,
                                      created_date TIMESTAMP NOT NULL,
                                      modified_date TIMESTAMP NOT NULL,
                                      PRIMARY KEY (member_daily_id)
);

CREATE TABLE board (
                       board_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       member_id BIGINT NOT NULL,
                       board_title VARCHAR(100) NOT NULL,
                       board_content VARCHAR(255) NOT NULL,
                       view_count NUMERIC(20) NOT NULL,
                       like_count BIGINT NOT NULL DEFAULT 0,
                       comment_count BIGINT NOT NULL DEFAULT 0,
                       board_type VARCHAR(20) NOT NULL,
                       created_date TIMESTAMP NOT NULL,
                       modified_date TIMESTAMP NOT NULL,
                       PRIMARY KEY (board_id)
);

CREATE TABLE board_comment (
                               comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               member_id BIGINT NOT NULL,
                               board_id BIGINT NOT NULL,
                               content VARCHAR(100) NOT NULL,
                               created_date TIMESTAMP NOT NULL,
                               PRIMARY KEY (comment_id)
);

CREATE TABLE board_like (
                            board_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            member_id BIGINT NOT NULL,
                            board_id BIGINT NOT NULL,
                            created_date TIMESTAMP NOT NULL,
                            PRIMARY KEY (board_like_id)
);

CREATE TABLE bookmark (
                          bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          member_id BIGINT NOT NULL,
                          board_id BIGINT NOT NULL,
                          created_date TIMESTAMP NOT NULL,
                          PRIMARY KEY (bookmark_id)
);

CREATE TABLE food (
                      food_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      food_name VARCHAR(50) NOT NULL,
                      manufacturer VARCHAR(50),
                      unit_kcal DECIMAL(4,1) NOT NULL,
                      unit_weight BIGINT NOT NULL,
                      PRIMARY KEY (food_id)
);

CREATE TABLE nutrition_category (
                                    food_cate_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    category VARCHAR(10) NOT NULL,
                                    PRIMARY KEY (food_cate_id)
);

CREATE TABLE nutrition_detail (
                                  nutrition_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  food_id BIGINT NOT NULL,
                                  food_cate_id BIGINT NOT NULL,
                                  nutrition_nm VARCHAR(50) NOT NULL,
                                  amount NUMERIC(4,1) NOT NULL,
                                  unit_weight BIGINT NOT NULL,
                                  PRIMARY KEY (nutrition_id)
);

CREATE TABLE team (
                      team_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      member_id BIGINT NOT NULL,
                      team_title VARCHAR(100) NOT NULL,
                      team_description VARCHAR(255),
                      team_img VARCHAR(255) NOT NULL,
                      team_current_members INT NOT NULL DEFAULT 1,
                      team_max_members BIGINT NOT NULL DEFAULT 6,
                      created_date TIMESTAMP NOT NULL,
                      modified_date TIMESTAMP NOT NULL,
                      PRIMARY KEY (team_id)
);

CREATE TABLE team_member_status (
                                    team_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    member_id BIGINT NOT NULL,
                                    team_id BIGINT NOT NULL,
                                    status VARCHAR(10) NOT NULL,
                                    created_date TIMESTAMP NOT NULL,
                                    modified_date TIMESTAMP NOT NULL,
                                    team_role VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
                                    banned_reason VARCHAR(255),
                                    banned_date TIMESTAMP,
                                    left_date TIMESTAMP,
                                    PRIMARY KEY (team_member_id)
);

CREATE TABLE team_notification (
                                   team_alarm_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   team_id BIGINT NOT NULL,
                                   member_id BIGINT NOT NULL,
                                   notification_type VARCHAR(1) NOT NULL,
                                   created_date TIMESTAMP NOT NULL,
                                   PRIMARY KEY (team_alarm_id)
);

CREATE TABLE team_activity_feed (
                                    feed_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    member_id BIGINT NOT NULL,
                                    team_id BIGINT NOT NULL,
                                    activity_type VARCHAR(20) NOT NULL,
                                    activity_content VARCHAR(20),
                                    created_date TIMESTAMP NOT NULL,
                                    PRIMARY KEY (feed_id)
);

CREATE TABLE team_ranking_history (
                                      team_ranking_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      member_id BIGINT NOT NULL,
                                      team_id BIGINT NOT NULL,
                                      week_code VARCHAR(10) NOT NULL,
                                      point INT NOT NULL DEFAULT 0,
                                      ranking INT NOT NULL,
                                      created_date TIMESTAMP NOT NULL,
                                      PRIMARY KEY (team_ranking_id)
);

CREATE TABLE chat_room (
                           chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           team_id BIGINT NOT NULL,
                           PRIMARY KEY (chat_room_id)
);

CREATE TABLE team_notice (
                             team_notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             member_id BIGINT NOT NULL,
                             team_id BIGINT NOT NULL,
                             title VARCHAR(255) NOT NULL,
                             content VARCHAR(255),
                             created_date TIMESTAMP NOT NULL,
                             modified_date TIMESTAMP NOT NULL,
                             PRIMARY KEY (team_notice_id)
);

CREATE TABLE chat_detail (
                             chat_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             chat_room_id BIGINT NOT NULL,
                             member_id BIGINT NOT NULL,
                             chat_content VARCHAR(255) NOT NULL,
                             created_date TIMESTAMP NOT NULL,
                             PRIMARY KEY (chat_detail_id)
);

CREATE TABLE challenge (
                           challenge_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           challenge_title VARCHAR(20) NOT NULL,
                           challenge_content VARCHAR(255) NOT NULL,
                           challenge_start_date TIMESTAMP NOT NULL,
                           challenge_end_date TIMESTAMP NOT NULL,
                           challenge_type VARCHAR(20) NOT NULL,
                           PRIMARY KEY (challenge_id)
);

CREATE TABLE member_challenge_status (
                                         mcs_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                         member_id BIGINT NOT NULL,
                                         challenge_id BIGINT NOT NULL,
                                         created_date TIMESTAMP NOT NULL,
                                         PRIMARY KEY (mcs_id)
);

CREATE TABLE badge (
                       badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255) NOT NULL,
                       badge_image VARCHAR(255) NOT NULL,
                       created_date TIMESTAMP NOT NULL,
                       PRIMARY KEY (badge_id)
);

CREATE TABLE member_badge_status (
                                     mbs_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     member_id BIGINT NOT NULL,
                                     badge_id BIGINT NOT NULL,
                                     created_date TIMESTAMP NOT NULL,
                                     PRIMARY KEY (mbs_id)
);

CREATE TABLE stamp (
                       stamp_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(20) NOT NULL,
                       stamp_image VARCHAR(255) NOT NULL,
                       created_date TIMESTAMP NOT NULL,
                       PRIMARY KEY (stamp_id)
);

CREATE TABLE member_stamp_status (
                                     mss_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     stamp_id BIGINT NOT NULL,
                                     member_id BIGINT NOT NULL,
                                     created_date TIMESTAMP NOT NULL,
                                     PRIMARY KEY (mss_id)
);

CREATE TABLE notification (
                              notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              member_id BIGINT NOT NULL,
                              notification_content VARCHAR(255) NOT NULL,
                              is_checked BOOLEAN NOT NULL DEFAULT false,
                              notification_type TIMESTAMP NOT NULL,
                              created_date TIMESTAMP NOT NULL,
                              modified_date TIMESTAMP NOT NULL,
                              PRIMARY KEY (notification_id)
);

CREATE TABLE member_global_ranking (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       year_month CHAR (7) NOT NULL,
                                       member_id BIGINT NOT NULL,
                                       score INT NOT NULL,
                                       rank INT NOT NULL,
                                       recorded_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE member_team_ranking (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     team_id BIGINT NOT NULL,
                                     period_type VARCHAR(10) NOT NULL,
                                     period_value VARCHAR(10) NOT NULL,
                                     member_id BIGINT NOT NULL,
                                     score INT NOT NULL,
                                     rank INT NOT NULL,
                                     recorded_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE team_global_ranking (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     period_type VARCHAR(10) NOT NULL,
                                     period_value VARCHAR(10) NOT NULL,
                                     team_id BIGINT NOT NULL,
                                     total_score INT NOT NULL,
                                     rank INT NOT NULL,
                                     recorded_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
                                     PRIMARY KEY (id)
);

CREATE TABLE daily_mission (
                               mission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               mission_date DATE UNIQUE NOT NULL
);

CREATE TABLE behavior (
                          behavior_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(200) NOT NULL
);

CREATE TABLE daily_mission_behavior (
                                        daily_mission_behavior_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        mission_id BIGINT NOT NULL,
                                        behavior_id BIGINT NOT NULL
);

CREATE TABLE member_behavior_log (
                                     member_behavior_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     member_id BIGINT NOT NULL,
                                     behavior_id BIGINT NOT NULL,
                                     created_date TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ON team_member_status (member_id, team_id);

CREATE INDEX idx_member_global_ranking_month ON member_global_ranking (year_month);

CREATE INDEX idx_member_team_ranking ON member_team_ranking (team_id, period_value);

CREATE INDEX idx_team_global_ranking ON team_global_ranking (period_value);

COMMENT ON COLUMN member.provider_id IS '소셜에서 들어오는 provider';

COMMENT ON COLUMN member.member_img IS 'AWS S3의 URL그대로 기록하기';

COMMENT ON COLUMN member.gender IS 'M,F 중 하나';

COMMENT ON COLUMN member.member_status IS '0:정상, 1:탈퇴, 2:정지';

COMMENT ON COLUMN member_meal_log.intake_amount IS '단위는 항상 g 혹은 ml로 간주';

COMMENT ON COLUMN member_meal_log.intake_kcal IS '그램수, 먹은 양 기반으로 계산해서 저장';

COMMENT ON COLUMN member_meal_log.meal_type IS '0: 아침, 1:점심, 2:저녁, 3:간식 중 하나';

COMMENT ON COLUMN member_daily_summary.total_kcal IS '음식 섭취 기록 작성시에 계산';

COMMENT ON COLUMN board.board_type IS '1: BEFORE_AFTER, 2:RECIPE, 3:FREETALK';

COMMENT ON COLUMN nutrition_category.category IS '탄수화물, 단백질, 무기질, 지방 등';

COMMENT ON COLUMN nutrition_detail.unit_weight IS '100, 10 등';

COMMENT ON COLUMN team.team_img IS 'AWS의 URL을 그대로 사용합니다';

COMMENT ON COLUMN team_member_status.status IS '0:HOLD, 1:REGIST, 2:APPROVED, 3:REJECT 등';

COMMENT ON COLUMN team_notification.notification_type IS '1:물섭취, 2:칼로리섭취, 3:몸무게변화. 4:챌린지달성 등';

COMMENT ON COLUMN challenge.challenge_start_date IS '진행중인 챌린지 목록 불러올 때 사용';

COMMENT ON COLUMN notification.is_checked IS '알람 확인 시에 TRUE로 변경';

COMMENT ON COLUMN notification.notification_type IS '그룹 공지, 서버 공지, 가입 신청 왔음, 가입 신청 APPROVED, REJECTED 등';

ALTER TABLE team ADD CONSTRAINT FK_member_team FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_notification ADD CONSTRAINT FK_team_member_stauts_TO_team_notification FOREIGN KEY (team_id, member_id) REFERENCES team_member_status (team_id, member_id);

ALTER TABLE team_activity_feed ADD CONSTRAINT FK_team_member_stauts_TO_team_activity_feed FOREIGN KEY (member_id, team_id) REFERENCES team_member_status (member_id, team_id);

ALTER TABLE team_ranking_history ADD CONSTRAINT FK_team_member_status_TO_team_ranking_history FOREIGN KEY (member_id, team_id) REFERENCES team_member_status (member_id, team_id);

ALTER TABLE team_notice ADD CONSTRAINT FK_team_member_status_TO_team_notice FOREIGN KEY (member_id, team_id) REFERENCES team_member_status (member_id, team_id);

ALTER TABLE member_stamp_status ADD CONSTRAINT FK_member_TO_member_stamp_status FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_stamp_status ADD CONSTRAINT FK_stamp_TO_member_stamp_status FOREIGN KEY (stamp_id) REFERENCES stamp (stamp_id);

ALTER TABLE auth ADD CONSTRAINT FK_member_TO_auth_1 FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_meal_log ADD CONSTRAINT FK_member_TO_meal_log FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_meal_log ADD CONSTRAINT FK_food_TO_meal_log FOREIGN KEY (food_id) REFERENCES food (food_id);

ALTER TABLE member_daily_summary ADD CONSTRAINT FK_member_TO_summary FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_comment ADD CONSTRAINT FK_member_TO_bcomment FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_comment ADD CONSTRAINT FK_board_TO_bcomment FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE board_like ADD CONSTRAINT FK_member_TO_board_like FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE board_like ADD CONSTRAINT FK_board_TO_board_like FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE bookmark ADD CONSTRAINT FK_member_TO_bookmark FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE bookmark ADD CONSTRAINT FK_board_TO_bookmark FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE nutrition_detail ADD CONSTRAINT FK_food_TO_ndetail FOREIGN KEY (food_id) REFERENCES food (food_id);

ALTER TABLE nutrition_detail ADD CONSTRAINT FK_ncategory_TO_ndetail FOREIGN KEY (food_cate_id) REFERENCES nutrition_category (food_cate_id);

ALTER TABLE team_member_status ADD CONSTRAINT FK_member_TO_gmstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_member_status ADD CONSTRAINT FK_team_TO_gmstatus FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE chat_room ADD CONSTRAINT FK_team_TO_chat_room FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE chat_detail ADD CONSTRAINT FK_chat_room_TO_cdetail FOREIGN KEY (chat_room_id) REFERENCES chat_room (chat_room_id);

ALTER TABLE chat_detail ADD CONSTRAINT FK_member_TO_cdetail FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_challenge_status ADD CONSTRAINT FK_member_TO_mcstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_challenge_status ADD CONSTRAINT FK_challenge_TO_mcstatus FOREIGN KEY (challenge_id) REFERENCES challenge (challenge_id);

ALTER TABLE member_badge_status ADD CONSTRAINT FK_member_TO_mbstatus FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_badge_status ADD CONSTRAINT FK_badge_TO_mbstqatus FOREIGN KEY (badge_id) REFERENCES badge (badge_id);

ALTER TABLE notification ADD CONSTRAINT FK_member_TO_notification FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_global_ranking ADD CONSTRAINT FK_member_TO_member_global_ranking FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_team_ranking ADD CONSTRAINT FK_team_TO_member_team_ranking FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE member_team_ranking ADD CONSTRAINT FK_member_TO_member_team_ranking FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE team_global_ranking ADD CONSTRAINT FK_team_TO_team_global_ranking FOREIGN KEY (team_id) REFERENCES team (team_id);

ALTER TABLE daily_mission_behavior ADD CONSTRAINT FK_daily_mission_TO_daily_mission_behavior FOREIGN KEY (mission_id) REFERENCES daily_mission (mission_id);

ALTER TABLE daily_mission_behavior ADD CONSTRAINT FK_behavior_TO_daily_mission_behavior FOREIGN KEY (behavior_id) REFERENCES behavior (behavior_id);

ALTER TABLE member_behavior_log ADD CONSTRAINT FK_member_TO_member_behavior_log FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE member_behavior_log ADD CONSTRAINT FK_behavior_TO_member_behavior_log FOREIGN KEY (behavior_id) REFERENCES behavior (behavior_id);
